---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentry-redis-deployment
  namespace: sentry
  labels:
    layer: sentry
    env: all
    app: sentry-redis
    name: sentry-redis-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        layer: sentry
        env: all
        app: sentry-redis
        name: sentry-redis-server
    spec:
      containers:
        - name: sentry-redis
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
      volumes:
        - name: data
          hostPath:
            path: /opt/sentry/redis

---
kind: Service
apiVersion: v1
metadata:
  name: redis
  namespace: sentry
  labels:
    layer: sentry
    env: all
    app: sentry-redis
    name: sentry-redis-server
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    layer: sentry
    env: all
    app: sentry-redis
    name: sentry-redis-server