---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sentry-cron-deployment
  namespace: sentry
  labels:
    layer: sentry
    env: all
    app: sentry-cron
    name: sentry-cron-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        layer: sentry
        env: all
        app: sentry-cron
        name: sentry-cron-server
    spec:
      containers:
        - name: sentry-cron
          image: sentry:latest
          imagePullPolicy: IfNotPresent
          command: ["sentry","run","cron"]
          env:
            - name: SENTRY_SECRET_KEY
              value: ")(mjdgi6)=-3(okh1@rjpcbz08qh&6!-p2b^w366@1ucedu+x("
            - name: SENTRY_POSTGRES_HOST
              value: "postgres"
            - name: SENTRY_DB_PASSWORD
              value: "secret"
            - name: SENTRY_REDIS_HOST
              value: "redis"
            - name: SENTRY_DB_USER
              value: "sentry"
            - name: SENTRY_EMAIL_BACKEND
              value: "smtp"
            - name: SENTRY_EMAIL_HOST
              value: "smtp.exmail.qq.com"
            - name: SENTRY_EMAIL_PORT
              value: "587"
            - name: SENTRY_EMAIL_USER
              value: ""
            - name: SENTRY_SERVER_EMAIL
              value: ""
            - name: SENTRY_EMAIL_PASSWORD
              value: ""
            - name: SENTRY_EMAIL_USE_TLS
              value: "true"